//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicleDetail
    {
        public int VehicleId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string RegNo { get; set; }
        public string ModelNo { get; set; }
        public string MakeYear { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual tblLogin tblLogin { get; set; }
        public virtual tblVehicleOwnerDetail tblVehicleOwnerDetail { get; set; }
    }
}
